# prometheus.yaml
global:
  scrape_interval: 1s
  evaluation_interval: 2s

scrape_configs:
  - job_name: vllm
    static_configs:
      - targets:
          - '10.0.20.128:8000'
          - '10.0.20.133:8000'
          - '10.0.20.133:8001'
          - '10.0.20.133:8002'
          - '10.0.20.133:8003'